// lib/cities.js - Pan India 50+ Cities
export const cities = [
  // Metro Cities
  { name: "Mumbai", state: "Maharashtra", code: "mumbai", population: "2.5Cr", searchVolume: "high" },
  { name: "Delhi", state: "Delhi", code: "delhi", population: "3Cr", searchVolume: "high" },
  { name: "Bangalore", state: "Karnataka", code: "bangalore", population: "1.5Cr", searchVolume: "high" },
  { name: "Hyderabad", state: "Telangana", code: "hyderabad", population: "1Cr", searchVolume: "high" },
  { name: "Chennai", state: "Tamil Nadu", code: "chennai", population: "1.1Cr", searchVolume: "high" },
  { name: "Kolkata", state: "West Bengal", code: "kolkata", population: "1.5Cr", searchVolume: "high" },
  { name: "Pune", state: "Maharashtra", code: "pune", population: "70L", searchVolume: "high" },
  { name: "Ahmedabad", state: "Gujarat", code: "ahmedabad", population: "80L", searchVolume: "high" },
  
  // Tier-1 Cities
  { name: "Jaipur", state: "Rajasthan", code: "jaipur", population: "40L", searchVolume: "medium" },
  { name: "Lucknow", state: "Uttar Pradesh", code: "lucknow", population: "35L", searchVolume: "medium" },
  { name: "Nagpur", state: "Maharashtra", code: "nagpur", population: "30L", searchVolume: "medium" },
  { name: "Indore", state: "Madhya Pradesh", code: "indore", population: "32L", searchVolume: "medium" },
  { name: "Bhopal", state: "Madhya Pradesh", code: "bhopal", population: "28L", searchVolume: "medium" },
  { name: "Surat", state: "Gujarat", code: "surat", population: "65L", searchVolume: "medium" },
  { name: "Vadodara", state: "Gujarat", code: "vadodara", population: "22L", searchVolume: "medium" },
  { name: "Patna", state: "Bihar", code: "patna", population: "25L", searchVolume: "medium" },
  { name: "Ranchi", state: "Jharkhand", code: "ranchi", population: "15L", searchVolume: "medium" },
  { name: "Bhubaneswar", state: "Odisha", code: "bhubaneswar", population: "18L", searchVolume: "medium" },
  { name: "Chandigarh", state: "Chandigarh", code: "chandigarh", population: "12L", searchVolume: "medium" },
  { name: "Dehradun", state: "Uttarakhand", code: "dehradun", population: "10L", searchVolume: "low" },
  { name: "Guwahati", state: "Assam", code: "guwahati", population: "12L", searchVolume: "low" },
  
  // Tier-2 Cities
  { name: "Agra", state: "Uttar Pradesh", code: "agra", population: "20L", searchVolume: "medium" },
  { name: "Aligarh", state: "Uttar Pradesh", code: "aligarh", population: "10L", searchVolume: "low" },
  { name: "Amritsar", state: "Punjab", code: "amritsar", population: "15L", searchVolume: "medium" },
  { name: "Aurangabad", state: "Maharashtra", code: "aurangabad", population: "15L", searchVolume: "low" },
  { name: "Bareilly", state: "Uttar Pradesh", code: "bareilly", population: "10L", searchVolume: "low" },
  { name: "Belgaum", state: "Karnataka", code: "belgaum", population: "8L", searchVolume: "low" },
  { name: "Bhagalpur", state: "Bihar", code: "bhagalpur", population: "5L", searchVolume: "low" },
  { name: "Bhilai", state: "Chhattisgarh", code: "bhilai", population: "10L", searchVolume: "low" },
  { name: "Bhiwandi", state: "Maharashtra", code: "bhiwandi", population: "9L", searchVolume: "low" },
  { name: "Bikaner", state: "Rajasthan", code: "bikaner", population: "8L", searchVolume: "low" },
  { name: "Bokaro", state: "Jharkhand", code: "bokaro", population: "8L", searchVolume: "low" },
  { name: "Coimbatore", state: "Tamil Nadu", code: "coimbatore", population: "25L", searchVolume: "medium" },
  { name: "Cuttack", state: "Odisha", code: "cuttack", population: "8L", searchVolume: "low" },
  { name: "Dhanbad", state: "Jharkhand", code: "dhanbad", population: "15L", searchVolume: "low" },
  { name: "Durgapur", state: "West Bengal", code: "durgapur", population: "10L", searchVolume: "low" },
  { name: "Ernakulam", state: "Kerala", code: "ernakulam", population: "15L", searchVolume: "medium" },
  { name: "Faridabad", state: "Haryana", code: "faridabad", population: "18L", searchVolume: "medium" },
  { name: "Firozabad", state: "Uttar Pradesh", code: "firozabad", population: "7L", searchVolume: "low" },
  { name: "Gandhinagar", state: "Gujarat", code: "gandhinagar", population: "8L", searchVolume: "low" },
  { name: "Gaya", state: "Bihar", code: "gaya", population: "5L", searchVolume: "low" },
  { name: "Ghaziabad", state: "Uttar Pradesh", code: "ghaziabad", population: "25L", searchVolume: "medium" },
  { name: "Gorakhpur", state: "Uttar Pradesh", code: "gorakhpur", population: "12L", searchVolume: "low" },
  { name: "Gulbarga", state: "Karnataka", code: "gulbarga", population: "8L", searchVolume: "low" },
  { name: "Guntur", state: "Andhra Pradesh", code: "guntur", population: "10L", searchVolume: "low" },
  { name: "Gurgaon", state: "Haryana", code: "gurgaon", population: "25L", searchVolume: "high" },
  { name: "Gwalior", state: "Madhya Pradesh", code: "gwalior", population: "15L", searchVolume: "medium" },
  { name: "Hubli", state: "Karnataka", code: "hubli", population: "12L", searchVolume: "low" },
  { name: "Jabalpur", state: "Madhya Pradesh", code: "jabalpur", population: "15L", searchVolume: "low" },
  { name: "Jalandhar", state: "Punjab", code: "jalandhar", population: "12L", searchVolume: "medium" },
  { name: "Jammu", state: "Jammu & Kashmir", code: "jammu", population: "8L", searchVolume: "low" },
  { name: "Jamnagar", state: "Gujarat", code: "jamnagar", population: "8L", searchVolume: "low" },
  { name: "Jamshedpur", state: "Jharkhand", code: "jamshedpur", population: "15L", searchVolume: "medium" },
  { name: "Jhansi", state: "Uttar Pradesh", code: "jhansi", population: "8L", searchVolume: "low" },
  { name: "Jodhpur", state: "Rajasthan", code: "jodhpur", population: "15L", searchVolume: "medium" },
  { name: "Kakinada", state: "Andhra Pradesh", code: "kakinada", population: "5L", searchVolume: "low" },
  { name: "Kannur", state: "Kerala", code: "kannur", population: "7L", searchVolume: "low" },
  { name: "Kanpur", state: "Uttar Pradesh", code: "kanpur", population: "30L", searchVolume: "medium" },
  { name: "Karnal", state: "Haryana", code: "karnal", population: "10L", searchVolume: "low" },
  { name: "Kochi", state: "Kerala", code: "kochi", population: "20L", searchVolume: "high" },
  { name: "Kohima", state: "Nagaland", code: "kohima", population: "3L", searchVolume: "low" },
  { name: "Kolhapur", state: "Maharashtra", code: "kolhapur", population: "12L", searchVolume: "low" },
  { name: "Kollam", state: "Kerala", code: "kollam", population: "8L", searchVolume: "low" },
  { name: "Kota", state: "Rajasthan", code: "kota", population: "12L", searchVolume: "medium" },
  { name: "Kozhikode", state: "Kerala", code: "kozhikode", population: "15L", searchVolume: "medium" }
];

export const getCityByCode = (code) => cities.find(c => c.code === code);
export const getPopularCities = () => cities.filter(c => c.searchVolume === "high");
export const getTier1Cities = () => cities.filter(c => c.searchVolume === "medium");
